[project]
name = "autocoder-plugin-xchat"
version = "0.1.0"
description = "xChat is a modern, interactive chat interface plugin for AutoCoder, featuring enhanced user experience, and powerful coding assistance capabilities."
readme = "README.md"
authors = [
    { name = "Pan Fan", email = "nightsailer@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "auto-coder>=0.1.310",
    "textual>=3.0.0",
    "watchfiles>=0.10.0",
    "ruamel.yaml>=0.18.10",
    "msgspec>=0.19.0",
]

[project.scripts]
autocoder-plugin-xchat = "autocoder_plugin_xchat:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
